services:
  backend-reverse-proxy:
    image: sxmlet/udagram-reverse-proxy
    build:
      context: udagram-reverse-proxy

  backend-feed:
    image: sxmlet/udagram-api-feed
    build:
      context: udagram-api-feed

  backend-user:
    image: sxmlet/udagram-api-user
    build:
      context: udagram-api-user

  frontend:
    image: sxmlet/udagram-frontend
    build:
      context: udagram-frontend
