version: 2.1

jobs:
  build:
    machine:
       image: ubuntu-2204:2023.02.1
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    environment:
      REPO: sxmlet
    steps:
      - checkout
      - run: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run: make build
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps:
            - run: make publish-images

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  main:
    jobs:
      - build
