version: 2.1

jobs:
  build:
    machine:
       image: ubuntu-2204:2023.02.1
    environment:
      REPO: sxmlet
    steps:
      - checkout
      - run:
          name: Build docker image
          command: make build
      - run:
          name: Log in to hub.docker.com
          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Publish docker image
          command: make publish-images

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only: /main/
