apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
  labels:
    app: udagram-frontend
spec:
  replicas: 1
  template:
    metadata:
      name: udagram-frontend
      labels:
        app: udagram-frontend
    spec:
      containers:
        - name: udagram-frontend
          image: sxmlet/udagram-frontend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      restartPolicy: Always
  selector:
    matchLabels:
      app: udagram-frontend
