apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverse-proxy
  labels:
    app: udagram-reverse-proxy
spec:
  replicas: 1
  template:
    metadata:
      name: udagram-reverse-proxy
      labels:
        app: udagram-reverse-proxy
    spec:
      containers:
        - name: udagram-reverse-proxy
          image: sxmlet/udagram-reverse-proxy
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      restartPolicy: Always
  selector:
    matchLabels:
      app: udagram-reverse-proxy
