apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-user
  labels:
    app: udagram-api-user
spec:
  replicas: 1
  template:
    metadata:
      name: udagram-api-user
      labels:
        app: udagram-api-user
    spec:
      containers:
        - name: udagram-api-user
          image: sxmlet/udagram-api-user
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 500m
          ports:
            - containerPort: 8080
          env:
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: AWS_BUCKET
                  name: udagram
            - name: UDAGRAM_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: UDAGRAM_ACCESS_KEY_ID
                  name: secrets
            - name: UDAGRAM_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: UDAGRAM_SECRET_ACCESS_KEY
                  name: secrets
            - name: UDAGRAM_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  key: UDAGRAM_SESSION_TOKEN
                  name: secrets
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: secrets
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: secrets
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_DB
                  name: secrets
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_HOST
                  name: secrets
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET
                  name: secrets
      restartPolicy: Always
  selector:
    matchLabels:
      app: udagram-api-user
