apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-frontend
  name: udagram-frontend-srv
  namespace: default
spec:
  selector:
    app: udagram-frontend
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}