apiVersion: v1
kind: Service
metadata:
  name: udagram-api-feed-srv
  namespace: default
spec:
  selector:
    app: udagram-api-feed-srv
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
