apiVersion: v1
kind: Service
metadata:
  name: udagram-reverse-proxy-srv
  namespace: default
spec:
  selector:
    app: udagram-reverse-proxy-srv
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: NodePort
